### Import News
POST http://localhost:8080/news/import

###

### Register User

POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "Yashwanth",
    "email": "yash2@gmail.com",
    "password": "123456"
}

###
### Login

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "test1@gmail.com",
  "password": "123456"
}

###

GET http://localhost:8080/history
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MUBnbWFpbC5jb20iLCJpYXQiOjE3ODQ0NTkyMzQsImV4cCI6MTc4NDU0NTYzNH0.dc8ZVj5yv_hYcG-FDgF93DUaVyxO69Lb5vMCVmxSq0A

###
POST http://localhost:8080/news/1/regenerate-ai
