### Import News
POST http://localhost:8080/news/import

###

### Register User

POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "Yashwanth",
    "email": "yash2@gmail.com",
    "password": "123456"
}

###
### Login

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "yash2@gmail.com",
  "password": "123456"
}

###

GET http://localhost:8080/news
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5YXNoMkBnbWFpbC5jb20iLCJpYXQiOjE3ODQwMTg2MTcsImV4cCI6MTc4NDEwNTAxN30._Ca7WV6W8CYpgQ7bPpGHqZEJ21gZgNdKuAeP2xo7QBw
